LD = ld 
AS = as
ASFLAGS_THUMB = -mthumb-interwork
LDFLAGS_THUMB = --thumb-entry=_start

CC = gcc
CFLAGS = -O2 -Wall
LFLAGS =


all:	exit_asm


exit_asm:	exit_asm.o
	$(LD) $(LDFLAGS) -o exit_asm exit_asm.o

exit_asm.o:	exit_asm.s
	$(AS) $(ASFLAGS) -o exit_asm.o exit_asm.s


submit:	exit_asm.s Makefile README
	tar -czvf P3_FSEsubmit.tar.gz exit_asm.s Makefile README

clean:
	rm -f *~ *.o exit_asm